name: "Charlie's Rethinking"
title: Charlie's Rethinking
email: forcemz@outlook.com
description: "Reflections"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: sinopre
github_username:  fcharlie
title_image: "https://s.gravatar.com/avatar/c1bfa439ee1031748f5af71f0c11dbb6?s=500"
post_limit: 5

timezone: Asia/Shanghai

footer_left: "<a href=\"https://github.com/jacobtomlinson/carte-noire\">Carte Noir</a> theme by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_center: "&lt;/&gt; on <a href=\"https://github.com/fcharlie/fcharlie.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"
footer_right: "<a href=\"/links/\">友情链接</a>"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

permalink: pretty
exclude: [vendor]
